---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "apk"
  name: "apk-svc"
spec:
  ports:
  - name: "port-1-apk-svc"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  - name: "port-2-apk-svc"
    port: 9443
    protocol: "TCP"
    targetPort: 9443
  selector:
    app: "apk"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "apk"
  name: "apk-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "apk"
  template:
    metadata:
      labels:
        app: "apk"
    spec:
      containers:
      - image: "lakshithag/apk-sts:latest"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "apk-deployment"
        ports:
        - containerPort: 8080
          name: "port-1-apk-svc"
          protocol: "TCP"
        - containerPort: 9443
          name: "port-2-apk-svc"
          protocol: "TCP"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
      nodeSelector: {}
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "apk"
  name: "apk-hpa"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "apk-deployment"
  targetCPUUtilizationPercentage: 50
